<?php

namespace App\Services;

use App\Models\Sale;
use App\Models\SaleItem;
use App\Models\Wastage;
use Carbon\Carbon;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;

/**
 * The "Barista AI" 30-day sales forecast + confidence scoring, shared by
 * DashboardController::getAIInsights() and Admin/AnalyticsController::index()
 * — both used to carry an independent, near-identical ~80-line copy of this
 * logic while caching the result under the same literal key
 * ('barista_forecast_deep', 1 hour TTL). Since Cache::remember() only runs
 * the closure on a miss, whichever endpoint was hit first each hour silently
 * decided what the OTHER endpoint got back too — and the two copies had
 * already drifted (the dashboard version had richer confidence scoring:
 * confidence_label, forecast_range_low/high, a >200-transaction special
 * case) — so the "loser" endpoint could return an incomplete shape
 * depending on request order. This service is the single source of truth
 * both controllers now call.
 */
class BaristaForecastService
{
    /** Regenerated by ai:warm-forecast on the scheduler; 1h means "due a refresh". */
    private const FRESH_KEY = 'barista_forecast_deep';

    private const FRESH_TTL = 3600;

    /**
     * A much longer-lived copy of the last good forecast. Its only job is to
     * give a web request something to return instantly when FRESH_KEY has
     * aged out, so nobody sits behind a live AI call. See getForecast().
     */
    private const STALE_KEY = 'barista_forecast_deep_stale';

    private const STALE_TTL = 86400;

    /**
     * @param  bool  $force  Regenerate even on a cache hit. Reserved for the
     *                       scheduled warmer — a web request must never pass
     *                       true, that is the blocking behaviour this exists
     *                       to keep off the request path.
     */
    public function getForecast(AIService $ai, bool $force = false): array
    {
        $thirtyDaysAgo = Carbon::now()->subDays(30);

        $historicalSales = Sale::revenue()
            ->selectRaw('DATE(created_at) as date, SUM(total_amount) as total')
            ->where('created_at', '>=', $thirtyDaysAgo)
            ->groupBy('date')
            ->orderBy('date', 'ASC')
            ->get()
            ->pluck('total', 'date')
            ->toArray();

        $daysOfData = count($historicalSales);
        $transactionCount = Sale::revenue()
            ->where('created_at', '>=', $thirtyDaysAgo)
            ->count();

        // --- ADAPTIVE DATA GATE ---
        // We allow AI analysis even with 1 day of data, but flag it as "Calibrating".
        if ($daysOfData < 1) {
            return [
                'is_calibrating' => true,
                'calibration_days_remaining' => 14 - $daysOfData,
                'meta' => [
                    'transaction_count' => $transactionCount,
                    'days_of_data' => $daysOfData,
                    'is_calibrating' => true,
                    'confidence_score' => 1,
                    'confidence_label' => 'Awaiting First Sale',
                    'confidence_max' => 7,
                ],
                'forecast_total' => 0,
                'daily_forecast' => [],
                'trend_analysis' => 'Waiting for the first transaction to begin analysis...',
                'predicted_top_products' => [],
                'demand_risk_alerts' => [],
                'strategic_advice' => 'Start recording sales to activate Barista AI.',
                'context_tags' => ['Setup Mode'],
            ];
        }

        if (! $force) {
            $cached = Cache::get(self::FRESH_KEY);
            if ($cached) {
                return $cached;
            }

            // Fresh copy has aged out. Hand back the last good one rather than
            // holding the request open for a live multi-provider AI call — that
            // cascade measured ~9s on a trivial dataset, and since FRESH_TTL is
            // an hour, whoever opened the Insights modal first after a login
            // paid it every single time. ai:warm-forecast keeps this topped up
            // in the background, so a stale hit is at most one scheduler
            // interval behind, not a day.
            $stale = Cache::get(self::STALE_KEY);
            if ($stale) {
                return $stale;
            }
        }

        $result = (function () use ($ai, $historicalSales, $daysOfData, $thirtyDaysAgo, $transactionCount) {
            $seventyTwoHoursAgo = Carbon::now()->subHours(72);

            $productPerformance = SaleItem::whereHas('sale', fn ($q) => $q->where('status', '!=', 'cancelled'))
                ->select('item_name', DB::raw('SUM(quantity) as total_qty'))
                ->where('created_at', '>=', $thirtyDaysAgo)
                ->groupBy('item_name')
                ->orderByDesc('total_qty')
                ->get()
                ->pluck('total_qty', 'item_name')
                ->toArray();

            // 72-hour window for sharp demand risk detection.
            $recentPerformance = SaleItem::whereHas('sale', fn ($q) => $q->where('status', '!=', 'cancelled'))
                ->select('item_name', DB::raw('SUM(quantity) as total_qty'))
                ->where('created_at', '>=', $seventyTwoHoursAgo)
                ->groupBy('item_name')
                ->get()
                ->pluck('total_qty', 'item_name')
                ->toArray();

            $wastageData = Wastage::with('ingredient')
                ->where('created_at', '>=', Carbon::now()->subDays(7))
                ->get()
                ->map(fn ($w) => [
                    'item' => $w->ingredient->name ?? 'Unknown',
                    'quantity' => $w->quantity,
                    'reason' => $w->reason,
                    'date' => $w->created_at->format('Y-m-d'),
                ])->toArray();

            $aiResult = $ai->analyzeSalesTrends($historicalSales, $productPerformance, $wastageData, $daysOfData, $recentPerformance);

            if (! $aiResult) {
                // Every provider failed. Return a well-formed placeholder
                // (same shape the "calibrating" branch above uses) instead of
                // null — this used to violate getForecast()'s own `: array`
                // return type and crash the dashboard/analytics page with a
                // 500 whenever the AI stack was entirely down. Deliberately
                // NOT cached (see call site): a transient outage shouldn't
                // lock every consumer into "AI unavailable" for a full hour.
                return [
                    'is_calibrating' => false,
                    'calibration_days_remaining' => 0,
                    'meta' => [
                        'transaction_count' => $transactionCount,
                        'days_of_data' => $daysOfData,
                        'is_calibrating' => false,
                        'confidence_score' => 0,
                        'confidence_label' => 'Unavailable',
                        'confidence_max' => 7,
                    ],
                    'forecast_total' => 0,
                    'daily_forecast' => [],
                    'trend_analysis' => 'The AI forecasting stack is temporarily unavailable. Please check back shortly.',
                    'predicted_top_products' => [],
                    'demand_risk_alerts' => [],
                    'strategic_advice' => 'Barista AI could not be reached — try again in a few minutes.',
                    'context_tags' => ['AI Unavailable'],
                ];
            }

            // Formatting daily forecast day labels.
            if (isset($aiResult['daily_forecast']) && is_array($aiResult['daily_forecast'])) {
                foreach ($aiResult['daily_forecast'] as &$df) {
                    try {
                        if (isset($df['day']) && strlen($df['day']) > 3) {
                            $df['day'] = Carbon::parse($df['day'])->format('D');
                        }
                    } catch (\Exception $e) {
                    }
                }
            }

            if (isset($aiResult['strategic_advice'])) {
                Cache::put('barista_ai_brief', $aiResult['strategic_advice'], 3600);
            }

            // Calibration & confidence scoring.
            $targetDays = 14;

            $volatilityScore = 0;
            $mean = array_sum($historicalSales) / $daysOfData;
            $variance = 0;
            foreach ($historicalSales as $val) {
                $variance += pow($val - $mean, 2);
            }
            $stdDev = sqrt($variance / $daysOfData);
            $cv = $mean > 0 ? ($stdDev / $mean) : 0;

            if ($cv > 0.4) {
                $volatilityScore = 2;
            } elseif ($cv > 0.2) {
                $volatilityScore = 1;
            }

            $confidenceScore = max(1, min($daysOfData, 7) - $volatilityScore);

            if ($transactionCount > 200 && $daysOfData >= $targetDays && $volatilityScore === 0) {
                $confidenceScore = 7;
            }

            $confidenceLabels = [
                0 => 'None', 1 => 'Insecure', 2 => 'Low', 3 => 'Emerging', 4 => 'Moderate', 5 => 'Good', 6 => 'High', 7 => 'Excellent',
            ];

            $aiResult['is_calibrating'] = $daysOfData < $targetDays;
            $aiResult['calibration_days_remaining'] = max(0, $targetDays - $daysOfData);
            $aiResult['meta'] = [
                'transaction_count' => $transactionCount,
                'days_of_data' => $daysOfData,
                'is_calibrating' => $daysOfData < $targetDays,
                'calibration_days_remaining' => max(0, $targetDays - $daysOfData),
                'confidence_score' => $confidenceScore,
                'confidence_label' => $confidenceLabels[min($confidenceScore, 7)] ?? 'Unknown',
                'confidence_max' => 7,
                'volatility_detected' => $volatilityScore > 0,
            ];

            if (isset($aiResult['forecast_total'])) {
                $total = $aiResult['forecast_total'];
                $rangeVariance = max(0.1, (1.0 - ($confidenceScore / 7)) * 0.4);
                $aiResult['forecast_range_low'] = $total * (1 - $rangeVariance);
                $aiResult['forecast_range_high'] = $total * (1 + $rangeVariance);
            }

            return $aiResult;
        })();

        // Only cache genuine AI results — an "AI unavailable" placeholder
        // (context_tags === ['AI Unavailable']) must not be locked in for the
        // full hour, so the next request gets a fresh retry instead of a
        // guaranteed-stale failure message. For the same reason it must never
        // become the stale fallback either, or one outage would pin "AI
        // unavailable" on the dashboard for a day.
        if (($result['context_tags'] ?? []) !== ['AI Unavailable']) {
            Cache::put(self::FRESH_KEY, $result, self::FRESH_TTL);
            Cache::put(self::STALE_KEY, $result, self::STALE_TTL);
        }

        return $result;
    }
}
